pr: none
trigger: none

pool: pins-odt-agent-pool

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.20.2
  pipelines:
    - pipeline: pr
      source: Inspector Programming PoC - PR
      trigger:
        branches:
          include:
            - main

steps:
  - checkout: self
  - template: steps/node_script.yml@templates
    parameters:
      nodeVersion: 22
      script: npm ci
  - script: |
      source ~/.bashrc
      shopt -s extglob

      mkdir -p $(Build.Repository.LocalPath)/app/node_modules/
      cp -r -n -L $(Build.Repository.LocalPath)/node_modules/!(inspector-programming-poc-app) $(Build.Repository.LocalPath)/app/node_modules/
    displayName: Move node_modules
  - template: steps/node_script.yml@templates
    parameters:
      nodeVersion: 22
      workingDirectory: $(Build.Repository.LocalPath)/app
      script: npm run build
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: $(Build.Repository.LocalPath)/app
      includeRootFolder: false
      archiveFile: $(Build.ArtifactStagingDirectory)/pins-app-inspector-programming-poc.zip
  - task: AzureWebApp@1
    inputs:
      azureSubscription: Azure DevOps Pipelines - Inspector Programming PoC - Deployment
      appType: webAppLinux
      appName: pins-app-inspector-programming-poc
      package: $(Build.ArtifactStagingDirectory)/pins-app-inspector-programming-poc.zip
